### ISSUE TITLE
Code on Hackster.io is out of date

### ISSUE THREAD

**Issue by pjhatesgithub** [WildernessLabs/Meadow_Project_Samples#2]
The code on [this Hackster.io page](https://www.hackster.io/wilderness-labs/make-an-edgeasketch-with-meadow-6955c3) doesn't match what's on GitHub. It also doesn't compile.

**Comment by pjhatesgithub** [comment]
I'll amend that. The code on all the Hackster.io pages in out of date.

**Comment by ghita** [comment]
trying to build  MeadowMapleServo. It seems to use latest Meadow.Foundation.Web.Maple.Server but I cannot find a nuget for Maple.Server that includes the needed changes (e.g. use of IActionResult or other new additions)

**Comment by jorgedevs** [comment]
Heya,

Unfortunately, its been hard trying to keep the hackster code snippets up to date since we make more projects overtime, but we've been working hard to update as many as we can. We're also adding a message at the beginning of most projects saying when was the last update this project was working (like this: _Project updated to beta 6.2 (released on March 5th, 2022_). It it doesnt have that string, its likely the code snippets are still outdated and they're in the ToDo.

We have also updated the readme on this repo with Links to the corresponding Hackster projects or straight to the project's source code.

Hope this helps clear things up a bit, I'm closing this issue since this is an on-going task, but do free open another issue you're having with a particular project, and I can prioritize to work on that.

Best,
Jorge
